class Colors:
    WHITE = (255, 255, 255)
    BLACK = (15, 15, 23)
    DARK_SURFACE = (25, 25, 35)
    DARKER_SURFACE = (18, 18, 28)
    NEON_CYAN = (0, 255, 255)
    NEON_PINK = (255, 20, 147)
    NEON_GREEN = (57, 255, 20)
    NEON_PURPLE = (138, 43, 226)
    NEON_ORANGE = (255, 140, 0)
    NEON_BLUE = (30, 144, 255)
    NEON_YELLOW = (255, 255, 0)
    RED = (220, 38, 127)
    ORANGE = (255, 140, 0)
    YELLOW = (255, 193, 7)
    GREEN = (76, 175, 80)
    BLUE = (33, 150, 243)
    PURPLE = (156, 39, 176)
    CYAN = (0, 188, 212)
    PINK = (233, 30, 99)
    GRAY = (158, 158, 158)
    LIGHT_GRAY = (189, 189, 189)
    DARK_GRAY = (97, 97, 97)
    TEXT_SECONDARY = (158, 158, 158)
    UI_BG_COLOR = DARK_SURFACE
    UI_TEXT_COLOR = WHITE
    UI_TEXT_SECONDARY = TEXT_SECONDARY
    BONUS_GREEN = NEON_GREEN
    ACCENT_COLOR = NEON_CYAN

class GameSettings:
    SCREEN_WIDTH = 400
    SCREEN_HEIGHT = 700
    FPS = 60
    INITIAL_BLOCK_HEALTH = 1
    HEALTH_INCREASE_PER_ROUND = 1

class UI:
    TOP_UI_HEIGHT = 80
    BOTTOM_UI_HEIGHT = 120
    TITLE_FONT_SIZE = 48
    MENU_FONT_SIZE = 32
    MENU_ITEM_HEIGHT = 60
    MENU_START_Y = 300

class Ball:
    RADIUS = 8
    SPEED = 11
    COUNT_START = 1
    LAUNCH_DELAY = 80

class Block:
    SIZE = 56
    MARGIN = 1
    ROWS_MAX = 10
    START_Y = 120
    MOVE_DOWN_DISTANCE = SIZE + MARGIN
    TYPE_NORMAL = 0
    TYPE_BOMB = 1
    TYPE_SHIELD = 2
    TYPE_GHOST = 3
    BOMB_COLOR = (255, 69, 0)
    SHIELD_COLOR = (70, 130, 180)
    GHOST_COLOR = (147, 112, 219)
    BOMB_CHANCE = 0.08
    SHIELD_CHANCE = 0.06
    GHOST_CHANCE = 0.05
    GHOST_PASS_CHANCE = 0.4

class Bonus:
    BALL_RADIUS = 10
    BALL_SPAWN_CHANCE = 0.8

class Paddle:
    WIDTH = 100
    HEIGHT = 15
    SPEED = 8
    Y = GameSettings.SCREEN_HEIGHT - 50

class Brick:
    WIDTH = 75
    HEIGHT = 30
    ROWS = 5
    COLS = 10
    PADDING = 5
    OFFSET_TOP = 60
    POINTS = 10

class Game:
    STATE_TITLE = 0
    STATE_GAME = 1
    STATE_SETTINGS = 2
    STATE_RANKING = 3
    STATE_PAUSED = 4
    STATE_STATISTICS = 5
    STATE_REPLAY = 6
    STATE_MODE_SELECT = 7
    STATE_ACHIEVEMENTS = 8
    MODE_CLASSIC = 0
    MODE_TIME_ATTACK = 1
    MODE_SURVIVAL = 2
    MODE_PUZZLE = 3

class Combo:
    TIME_WINDOW = 2000
    MULTIPLIER_BASE = 1.5
    MULTIPLIER_INCREMENT = 0.5
    MAX_MULTIPLIER = 5.0
    MIN_COUNT = 2
    TEXT_COLOR = Colors.NEON_YELLOW
    GLOW_COLOR = (255, 255, 0, 100)

class Particle:
    EXPLOSION_COUNT = 15
    EXPLOSION_SPEED = 8
    EXPLOSION_LIFE = 30
    TRAIL_LENGTH = 8
    TRAIL_FADE_SPEED = 20
    SPARKLE_COUNT = 8
    SPARKLE_SPEED = 4
    SPARKLE_LIFE = 20

class Theme:
    DARK = "dark"
    LIGHT = "light"
    CHRISTMAS = "christmas"
    HALLOWEEN = "halloween"
    SPRING = "spring"
    SUMMER = "summer"
    LIGHT_WHITE = (255, 255, 255)
    LIGHT_BLACK = (240, 240, 245)
    LIGHT_SURFACE = (250, 250, 255)
    LIGHT_DARKER_SURFACE = (235, 235, 245)
    LIGHT_TEXT = (50, 50, 70)
    LIGHT_TEXT_SECONDARY = (120, 120, 140)
    CHRISTMAS_RED = (220, 20, 60)
    CHRISTMAS_GREEN = (34, 139, 34)
    CHRISTMAS_GOLD = (255, 215, 0)
    CHRISTMAS_WHITE = (255, 250, 250)
    CHRISTMAS_DARK = (25, 25, 35)
    HALLOWEEN_ORANGE = (255, 140, 0)
    HALLOWEEN_PURPLE = (128, 0, 128)
    HALLOWEEN_BLACK = (20, 20, 20)
    HALLOWEEN_GREEN = (50, 205, 50)
    HALLOWEEN_GRAY = (105, 105, 105)
    SPRING_PINK = (255, 182, 193)
    SPRING_GREEN = (144, 238, 144)
    SPRING_YELLOW = (255, 255, 224)
    SPRING_BLUE = (173, 216, 230)
    SPRING_WHITE = (248, 248, 255)
    SUMMER_BLUE = (0, 191, 255)
    SUMMER_YELLOW = (255, 215, 0)
    SUMMER_ORANGE = (255, 165, 0)
    SUMMER_CYAN = (0, 255, 255)
    SUMMER_WHITE = (255, 255, 255)
    BACKGROUNDS = {
        DARK: [(15, 15, 23), (25, 25, 35), (35, 35, 45)],
        LIGHT: [(240, 240, 245), (250, 250, 255), (255, 255, 255)],
        CHRISTMAS: [(25, 25, 35), (139, 0, 0), (0, 100, 0)],
        HALLOWEEN: [(20, 20, 20), (75, 0, 130), (255, 140, 0)],
        SPRING: [(248, 248, 255), (255, 182, 193), (144, 238, 144)],
        SUMMER: [(135, 206, 235), (255, 215, 0), (0, 191, 255)]
    }
    ROUND_CHANGES = {
        1: DARK,
        5: SPRING,
        10: SUMMER,
        15: HALLOWEEN,
        20: CHRISTMAS,
        25: LIGHT
    }

class Replay:
    MAX_ACTIONS = 10000
    SAVE_THRESHOLD = 1000

class Stats:
    UPDATE_INTERVAL = 1000

class Achievement:
    NOTIFICATION_DURATION = 3000
    PERFECT_ANGLE_TOLERANCE = 2
    PERFECT_ANGLES = [45, 90, 135]

class Shop:
    ITEMS = [
        {"name": "파워볼", "price": 100, "desc": "벽돌을 2배로 깸", "key": 1},
        {"name": "스피드볼", "price": 150, "desc": "공 속도 2배", "key": 2},
        {"name": "매그넘볼", "price": 200, "desc": "공 1개 남으면 모든 블록 제거", "key": 3},
        {"name": "블록 삭제", "price": 300, "desc": "모든 블록 즉시 삭제", "key": None},
    ]


# ===== 모듈 수준 상수 별칭 (하위 호환성) =====

# 색상
WHITE = Colors.WHITE
BLACK = Colors.BLACK
DARK_SURFACE = Colors.DARK_SURFACE
DARKER_SURFACE = Colors.DARKER_SURFACE
NEON_CYAN = Colors.NEON_CYAN
NEON_PINK = Colors.NEON_PINK
NEON_GREEN = Colors.NEON_GREEN
NEON_PURPLE = Colors.NEON_PURPLE
NEON_ORANGE = Colors.NEON_ORANGE
NEON_BLUE = Colors.NEON_BLUE
NEON_YELLOW = Colors.NEON_YELLOW
RED = Colors.RED
ORANGE = Colors.ORANGE
YELLOW = Colors.YELLOW
GREEN = Colors.GREEN
BLUE = Colors.BLUE
PURPLE = Colors.PURPLE
CYAN = Colors.CYAN
PINK = Colors.PINK
GRAY = Colors.GRAY
LIGHT_GRAY = Colors.LIGHT_GRAY
DARK_GRAY = Colors.DARK_GRAY
TEXT_SECONDARY = Colors.TEXT_SECONDARY
UI_BG_COLOR = Colors.UI_BG_COLOR
UI_TEXT_COLOR = Colors.UI_TEXT_COLOR
UI_TEXT_SECONDARY = Colors.UI_TEXT_SECONDARY
BONUS_GREEN = Colors.BONUS_GREEN
ACCENT_COLOR = Colors.ACCENT_COLOR

# 테마 색상
LIGHT_WHITE = Theme.LIGHT_WHITE
LIGHT_BLACK = Theme.LIGHT_BLACK
LIGHT_SURFACE = Theme.LIGHT_SURFACE
LIGHT_DARKER_SURFACE = Theme.LIGHT_DARKER_SURFACE
LIGHT_TEXT = Theme.LIGHT_TEXT
LIGHT_TEXT_SECONDARY = Theme.LIGHT_TEXT_SECONDARY
CHRISTMAS_RED = Theme.CHRISTMAS_RED
CHRISTMAS_GREEN = Theme.CHRISTMAS_GREEN
CHRISTMAS_GOLD = Theme.CHRISTMAS_GOLD
CHRISTMAS_WHITE = Theme.CHRISTMAS_WHITE
CHRISTMAS_DARK = Theme.CHRISTMAS_DARK
HALLOWEEN_ORANGE = Theme.HALLOWEEN_ORANGE
HALLOWEEN_PURPLE = Theme.HALLOWEEN_PURPLE
HALLOWEEN_BLACK = Theme.HALLOWEEN_BLACK
HALLOWEEN_GREEN = Theme.HALLOWEEN_GREEN
HALLOWEEN_GRAY = Theme.HALLOWEEN_GRAY
SPRING_PINK = Theme.SPRING_PINK
SPRING_GREEN = Theme.SPRING_GREEN
SPRING_YELLOW = Theme.SPRING_YELLOW
SPRING_BLUE = Theme.SPRING_BLUE
SPRING_WHITE = Theme.SPRING_WHITE
SUMMER_BLUE = Theme.SUMMER_BLUE
SUMMER_YELLOW = Theme.SUMMER_YELLOW
SUMMER_ORANGE = Theme.SUMMER_ORANGE
SUMMER_CYAN = Theme.SUMMER_CYAN
SUMMER_WHITE = Theme.SUMMER_WHITE
THEME_BACKGROUNDS = Theme.BACKGROUNDS
ROUND_THEME_CHANGES = Theme.ROUND_CHANGES
THEME_DARK = Theme.DARK
THEME_LIGHT = Theme.LIGHT
THEME_CHRISTMAS = Theme.CHRISTMAS
THEME_HALLOWEEN = Theme.HALLOWEEN
THEME_SPRING = Theme.SPRING
THEME_SUMMER = Theme.SUMMER

# 게임 설정
SCREEN_WIDTH = GameSettings.SCREEN_WIDTH
SCREEN_HEIGHT = GameSettings.SCREEN_HEIGHT
FPS = GameSettings.FPS
INITIAL_BLOCK_HEALTH = GameSettings.INITIAL_BLOCK_HEALTH
HEALTH_INCREASE_PER_ROUND = GameSettings.HEALTH_INCREASE_PER_ROUND

# UI
TOP_UI_HEIGHT = UI.TOP_UI_HEIGHT
BOTTOM_UI_HEIGHT = UI.BOTTOM_UI_HEIGHT
TITLE_FONT_SIZE = UI.TITLE_FONT_SIZE
MENU_FONT_SIZE = UI.MENU_FONT_SIZE
MENU_ITEM_HEIGHT = UI.MENU_ITEM_HEIGHT
MENU_START_Y = UI.MENU_START_Y

# 공
BALL_RADIUS = Ball.RADIUS
BALL_SPEED = Ball.SPEED
BALL_COUNT_START = Ball.COUNT_START
BALL_LAUNCH_DELAY = Ball.LAUNCH_DELAY

# 블록
BLOCK_SIZE = Block.SIZE
BLOCK_MARGIN = Block.MARGIN
BLOCKS_PER_ROW = 7
BLOCK_ROWS_MAX = Block.ROWS_MAX
BLOCK_START_Y = Block.START_Y
BLOCKS_MOVE_DOWN_DISTANCE = Block.MOVE_DOWN_DISTANCE
BLOCK_TYPE_NORMAL = Block.TYPE_NORMAL
BLOCK_TYPE_BOMB = Block.TYPE_BOMB
BLOCK_TYPE_SHIELD = Block.TYPE_SHIELD
BLOCK_TYPE_GHOST = Block.TYPE_GHOST
BOMB_BLOCK_COLOR = Block.BOMB_COLOR
SHIELD_BLOCK_COLOR = Block.SHIELD_COLOR
GHOST_BLOCK_COLOR = Block.GHOST_COLOR
BOMB_BLOCK_CHANCE = Block.BOMB_CHANCE
SHIELD_BLOCK_CHANCE = Block.SHIELD_CHANCE
GHOST_BLOCK_CHANCE = Block.GHOST_CHANCE
GHOST_BLOCK_PASS_CHANCE = Block.GHOST_PASS_CHANCE

# 보너스
BONUS_BALL_RADIUS = Bonus.BALL_RADIUS
BONUS_BALL_SPAWN_CHANCE = Bonus.BALL_SPAWN_CHANCE

# 게임 상태 및 모드
GAME_STATE_TITLE = Game.STATE_TITLE
GAME_STATE_GAME = Game.STATE_GAME
GAME_STATE_SETTINGS = Game.STATE_SETTINGS
GAME_STATE_RANKING = Game.STATE_RANKING
GAME_STATE_PAUSED = Game.STATE_PAUSED
GAME_STATE_STATISTICS = Game.STATE_STATISTICS
GAME_STATE_REPLAY = Game.STATE_REPLAY
GAME_STATE_MODE_SELECT = Game.STATE_MODE_SELECT
GAME_STATE_ACHIEVEMENTS = Game.STATE_ACHIEVEMENTS
GAME_MODE_CLASSIC = Game.MODE_CLASSIC
GAME_MODE_TIME_ATTACK = Game.MODE_TIME_ATTACK
GAME_MODE_SURVIVAL = Game.MODE_SURVIVAL
GAME_MODE_PUZZLE = Game.MODE_PUZZLE

# 콤보
COMBO_TIME_WINDOW = Combo.TIME_WINDOW
COMBO_MULTIPLIER_BASE = Combo.MULTIPLIER_BASE
COMBO_MULTIPLIER_INCREMENT = Combo.MULTIPLIER_INCREMENT
MAX_COMBO_MULTIPLIER = Combo.MAX_MULTIPLIER
MIN_COMBO_COUNT = Combo.MIN_COUNT
COMBO_TEXT_COLOR = Combo.TEXT_COLOR
COMBO_GLOW_COLOR = Combo.GLOW_COLOR

# 파티클
EXPLOSION_PARTICLE_COUNT = Particle.EXPLOSION_COUNT
EXPLOSION_PARTICLE_SPEED = Particle.EXPLOSION_SPEED
EXPLOSION_PARTICLE_LIFE = Particle.EXPLOSION_LIFE
TRAIL_LENGTH = Particle.TRAIL_LENGTH
TRAIL_FADE_SPEED = Particle.TRAIL_FADE_SPEED
SPARKLE_PARTICLE_COUNT = Particle.SPARKLE_COUNT
SPARKLE_PARTICLE_SPEED = Particle.SPARKLE_SPEED
SPARKLE_PARTICLE_LIFE = Particle.SPARKLE_LIFE

# 리플레이
MAX_REPLAY_ACTIONS = Replay.MAX_ACTIONS
REPLAY_SAVE_THRESHOLD = Replay.SAVE_THRESHOLD

# 통계
STATS_UPDATE_INTERVAL = Stats.UPDATE_INTERVAL

# 업적
ACHIEVEMENT_NOTIFICATION_DURATION = Achievement.NOTIFICATION_DURATION
PERFECT_ANGLE_TOLERANCE = Achievement.PERFECT_ANGLE_TOLERANCE
PERFECT_ANGLES = Achievement.PERFECT_ANGLES

# 상점
SHOP_ITEMS = Shop.ITEMS

# 발사 설정
AIM_LINE_LENGTH = 200
MIN_LAUNCH_ANGLE = 10
MAX_LAUNCH_ANGLE = 170
LAUNCH_AREA_HEIGHT = 100

# 도전 모드
TIME_ATTACK_DURATION = 120
PUZZLE_MODE_BALLS = 10
SURVIVAL_SPEED_INCREASE = 0.1